export const popularIcons = [
  { slug: "github", name: "GitHub" },
  { slug: "gitlab", name: "GitLab" },
  { slug: "bitbucket", name: "Bitbucket" },
  { slug: "docker", name: "Docker" },
  { slug: "kubernetes", name: "Kubernetes" },
  { slug: "nginx", name: "Nginx" },
  { slug: "googlecloud", name: "Google Cloud" },
  { slug: "amazonwebservices", name: "AWS" },
  { slug: "microsoftazure", name: "Azure" },
  { slug: "vercel", name: "Vercel" },
  { slug: "netlify", name: "Netlify" },
  { slug: "cloudflare", name: "Cloudflare" },
  { slug: "digitalocean", name: "DigitalOcean" },
  { slug: "heroku", name: "Heroku" },
  { slug: "render", name: "Render" },
  { slug: "railway", name: "Railway" },
  { slug: "flydotio", name: "Fly.io" },
  { slug: "planetscale", name: "PlanetScale" },
  { slug: "gmail", name: "Gmail" },
  { slug: "googlecalendar", name: "Google Calendar" },
  { slug: "googledrive", name: "Google Drive" },
  { slug: "googlemeet", name: "Google Meet" },
  { slug: "googledocs", name: "Google Docs" },
  { slug: "googlemaps", name: "Google Maps" },
  { slug: "googlescholar", name: "Google Scholar" },
  { slug: "slack", name: "Slack" },
  { slug: "discord", name: "Discord" },
  { slug: "telegram", name: "Telegram" },
  { slug: "signal", name: "Signal" },
  { slug: "whatsapp", name: "WhatsApp" },
  { slug: "microsoftteams", name: "Microsoft Teams" },
  { slug: "zoom", name: "Zoom" },
  { slug: "notion", name: "Notion" },
  { slug: "linear", name: "Linear" },
  { slug: "jira", name: "Jira" },
  { slug: "trello", name: "Trello" },
  { slug: "asana", name: "Asana" },
  { slug: "figma", name: "Figma" },
  { slug: "penpot", name: "Penpot" },
  { slug: "canva", name: "Canva" },
  { slug: "dribbble", name: "Dribbble" },
  { slug: "behance", name: "Behance" },
  { slug: "unsplash", name: "Unsplash" },
  { slug: "youtube", name: "YouTube" },
  { slug: "twitch", name: "Twitch" },
  { slug: "spotify", name: "Spotify" },
  { slug: "apple", name: "Apple" },
  { slug: "applepodcasts", name: "Apple Podcasts" },
  { slug: "reddit", name: "Reddit" },
  { slug: "x", name: "X / Twitter" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "instagram", name: "Instagram" },
  { slug: "facebook", name: "Facebook" },
  { slug: "threads", name: "Threads" },
  { slug: "mastodon", name: "Mastodon" },
  { slug: "bluesky", name: "Bluesky" },
  { slug: "paypal", name: "PayPal" },
  { slug: "mercado_pago", name: "Mercado Pago" },
  { slug: "shopify", name: "Shopify" },
  { slug: "wordpress", name: "WordPress" },
  { slug: "medium", name: "Medium" },
  { slug: "devdotto", name: "Dev.to" },
  { slug: "stackoverflow", name: "Stack Overflow" },
  { slug: "stackexchange", name: "Stack Exchange" },
  { slug: "npm", name: "npm" },
  { slug: "yarn", name: "Yarn" },
  { slug: "pnpm", name: "pnpm" },
  { slug: "python", name: "Python" },
  { slug: "javascript", name: "JavaScript" },
  { slug: "typescript", name: "TypeScript" },
  { slug: "react", name: "React" },
  { slug: "nextdotjs", name: "Next.js" },
  { slug: "nodedotjs", name: "Node.js" },
  { slug: "deno", name: "Deno" },
  { slug: "tailwindcss", name: "Tailwind CSS" },
  { slug: "bootstrap", name: "Bootstrap" },
  { slug: "supabase", name: "Supabase" },
  { slug: "firebase", name: "Firebase" },
  { slug: "mongodb", name: "MongoDB" },
  { slug: "postgresql", name: "PostgreSQL" },
  { slug: "mysql", name: "MySQL" },
  { slug: "sqlite", name: "SQLite" },
  { slug: "redis", name: "Redis" },
  { slug: "grafana", name: "Grafana" },
  { slug: "prometheus", name: "Prometheus" },
  { slug: "datadog", name: "Datadog" },
  { slug: "sentry", name: "Sentry" },
  { slug: "codeberg", name: "Codeberg" },
  { slug: "sourceforge", name: "SourceForge" },
  { slug: "atlassian", name: "Atlassian" },
  { slug: "mailchimp", name: "Mailchimp" },
  { slug: "sendgrid", name: "SendGrid" },
  { slug: "cloudinary", name: "Cloudinary" },
  { slug: "chatgpt", name: "ChatGPT" },
  { slug: "openai", name: "OpenAI" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "huggingface", name: "Hugging Face" },
  { slug: "wikipedia", name: "Wikipedia" },
  { slug: "archiveofourown", name: "Archive of Our Own" },
  { slug: "imdb", name: "IMDb" },
  { slug: "letterboxd", name: "Letterboxd" },
  { slug: "goodreads", name: "Goodreads" },
  { slug: "sap", name: "SAP" },
  { slug: "microsoft", name: "Microsoft" },
  { slug: "microsoftoffice", name: "Microsoft Office" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "todoist", name: "Todoist" },
  { slug: "obsidian", name: "Obsidian" },
  { slug: "git", name: "Git" },
  { slug: "linux", name: "Linux" },
  { slug: "ubuntu", name: "Ubuntu" },
  { slug: "debian", name: "Debian" },
  { slug: "fedora", name: "Fedora" },
  { slug: "archlinux", name: "Arch Linux" },
  { slug: "manjaro", name: "Manjaro" },
  { slug: "alpinelinux", name: "Alpine Linux" },
  { slug: "codeberg", name: "Codeberg" },
  { slug: "sourcehut", name: "SourceHut" },
  { slug: "homebrew", name: "Homebrew" },
  { slug: "curl", name: "cURL" },
  { slug: "vim", name: "Vim" },
  { slug: "neovim", name: "Neovim" },
  { slug: "emacs", name: "Emacs" },
  { slug: "visualstudiocode", name: "VS Code" },
  { slug: "jetbrains", name: "JetBrains" },
  { slug: "webstorm", name: "WebStorm" },
  { slug: "intellijidea", name: "IntelliJ IDEA" },
  { slug: "pycharm", name: "PyCharm" },
  { slug: "goland", name: "GoLand" },
  { slug: "clion", name: "CLion" },
  { slug: "phpstorm", name: "PhpStorm" },
  { slug: "rust", name: "Rust" },
  { slug: "go", name: "Go" },
  { slug: "zig", name: "Zig" },
  { slug: "kotlin", name: "Kotlin" },
  { slug: "swift", name: "Swift" },
  { slug: "ruby", name: "Ruby" },
  { slug: "php", name: "PHP" },
  { slug: "cplusplus", name: "C++" },
  { slug: "csharp", name: "C#" },
  { slug: "java", name: "Java" },
  { slug: "elixir", name: "Elixir" },
  { slug: "erlang", name: "Erlang" },
  { slug: "haskell", name: "Haskell" },
  { slug: "clojure", name: "Clojure" },
  { slug: "scala", name: "Scala" },
  { slug: "lua", name: "Lua" },
  { slug: "perl", name: "Perl" },
  { slug: "r", name: "R" },
  { slug: "dart", name: "Dart" },
  { slug: "flutter", name: "Flutter" },
  { slug: "android", name: "Android" },
  { slug: "kotlin", name: "Kotlin" },
  { slug: "swift", name: "Swift" },
  { slug: "xcode", name: "Xcode" },
  { slug: "tmux", name: "tmux" },
  { slug: "zsh", name: "Zsh" },
  { slug: "bash", name: "Bash" },
  { slug: "postman", name: "Postman" },
  { slug: "insomnia", name: "Insomnia" },
  { slug: "jupyter", name: "Jupyter" },
  { slug: "anaconda", name: "Anaconda" },
  { slug: "minitab", name: "Minitab" },
  { slug: "matlab", name: "MATLAB" },
  { slug: "octave", name: "GNU Octave" },
  { slug: "tor", name: "Tor" },
  { slug: "tailwindcss", name: "Tailwind CSS" },
  { slug: "bulma", name: "Bulma" },
  { slug: "materialdesign", name: "Material Design" },
  { slug: "semanticuireact", name: "Semantic UI" },
  { slug: "chakraui", name: "Chakra UI" },
  { slug: "radixui", name: "Radix UI" },
  { slug: "shadcnui", name: "shadcn/ui" },
  { slug: "daisyui", name: "daisyUI" },
  { slug: "prettier", name: "Prettier" },
  { slug: "eslint", name: "ESLint" },
  { slug: "typescript", name: "TypeScript" },
  { slug: "sass", name: "Sass" },
  { slug: "less", name: "Less" },
  { slug: "stylus", name: "Stylus" },
  { slug: "webpack", name: "Webpack" },
  { slug: "rollupdotjs", name: "Rollup" },
  { slug: "esbuild", name: "esbuild" },
  { slug: "vite", name: "Vite" },
  { slug: "turbo", name: "Turbo" },
  { slug: "nx", name: "Nx" },
  { slug: "babel", name: "Babel" },
  { slug: "swc", name: "SWC" },
  { slug: "jest", name: "Jest" },
  { slug: "vitest", name: "Vitest" },
  { slug: "mocha", name: "Mocha" },
  { slug: "cypress", name: "Cypress" },
  { slug: "playwright", name: "Playwright" },
  { slug: "testinglibrary", name: "Testing Library" },
  { slug: "storybook", name: "Storybook" },
  { slug: "graphql", name: "GraphQL" },
  { slug: "apollographql", name: "Apollo GraphQL" },
  { slug: "relay", name: "Relay" },
  { slug: "prisma", name: "Prisma" },
  { slug: "drizzle", name: "Drizzle" },
  { slug: "typeorm", name: "TypeORM" },
  { slug: "sequelize", name: "Sequelize" },
  { slug: "mongoose", name: "Mongoose" },
  { slug: "knex", name: "Knex.js" },
  { slug: "betterstack", name: "Better Stack" },
  { slug: "sentry", name: "Sentry" },
  { slug: "datadog", name: "Datadog" },
  { slug: "newrelic", name: "New Relic" },
  { slug: "opentelemetry", name: "OpenTelemetry" },
  { slug: "cloudflare", name: "Cloudflare" },
  { slug: "fastly", name: "Fastly" },
  { slug: "akamai", name: "Akamai" },
  { slug: "githubactions", name: "GitHub Actions" },
  { slug: "gitlabci", name: "GitLab CI" },
  { slug: "circleci", name: "CircleCI" },
  { slug: "jenkins", name: "Jenkins" },
  { slug: "travisci", name: "Travis CI" },
  { slug: "terraform", name: "Terraform" },
  { slug: "ansible", name: "Ansible" },
  { slug: "puppet", name: "Puppet" },
  { slug: "chef", name: "Chef" },
  { slug: "saltproject", name: "Salt" },
  { slug: "vagrant", name: "Vagrant" },
  { slug: "packer", name: "Packer" },
  { slug: "nomad", name: "Nomad" },
  { slug: "consul", name: "Consul" },
  { slug: "vault", name: "Vault" },
  { slug: "nginxproxymanager", name: "Nginx Proxy Manager" },
  { slug: "caddy", name: "Caddy" },
  { slug: "haproxy", name: "HAProxy" },
  { slug: "traefikproxy", name: "Traefik" },
  { slug: "envoy", name: "Envoy" },
  { slug: "istio", name: "Istio" },
  { slug: "kong", name: "Kong" },
  { slug: "mysql", name: "MySQL" },
  { slug: "mariadb", name: "MariaDB" },
  { slug: "postgresql", name: "PostgreSQL" },
  { slug: "mongodb", name: "MongoDB" },
  { slug: "sqlite", name: "SQLite" },
  { slug: "cassandra", name: "Cassandra" },
  { slug: "couchdb", name: "CouchDB" },
  { slug: "neo4j", name: "Neo4j" },
  { slug: "redis", name: "Redis" },
  { slug: "memcached", name: "Memcached" },
  { slug: "rabbitmq", name: "RabbitMQ" },
  { slug: "kafka", name: "Apache Kafka" },
  { slug: "nats", name: "NATS" },
  { slug: "zeromq", name: "ZeroMQ" },
  { slug: "elasticsearch", name: "Elasticsearch" },
  { slug: "logstash", name: "Logstash" },
  { slug: "kibana", name: "Kibana" },
  { slug: "opensearch", name: "OpenSearch" },
  { slug: "splunk", name: "Splunk" },
  { slug: "graylog", name: "Graylog" },
  { slug: "loki", name: "Loki" },
  { slug: "tempo", name: "Tempo" },
  { slug: "mimir", name: "Mimir" },
  { slug: "pyroscope", name: "Pyroscope" },
  { slug: "thanos", name: "Thanos" },
  { slug: "victoriametrics", name: "VictoriaMetrics" },
  { slug: "clickhouse", name: "ClickHouse" },
  { slug: "druid", name: "Apache Druid" },
  { slug: "influxdb", name: "InfluxDB" },
  { slug: "timescaledb", name: "TimescaleDB" },
  { slug: "pinot", name: "Apache Pinot" },
  { slug: "airflow", name: "Apache Airflow" },
  { slug: "prefect", name: "Prefect" },
  { slug: "dagster", name: "Dagster" },
  { slug: "n8n", name: "n8n" },
  { slug: "zapier", name: "Zapier" },
  { slug: "make", name: "Make" },
  { slug: "ifttt", name: "IFTTT" },
  { slug: "huggingface", name: "Hugging Face" },
  { slug: "replicate", name: "Replicate" },
  { slug: "langchain", name: "LangChain" },
  { slug: "llama", name: "Llama" },
  { slug: "ollama", name: "Ollama" },
  { slug: "civitai", name: "Civitai" },
  { slug: "midjourney", name: "Midjourney" },
  { slug: "stabilityai", name: "Stability AI" },
  { slug: "runway", name: "Runway" },
  { slug: "deepgram", name: "Deepgram" },
  { slug: "assemblyai", name: "AssemblyAI" },
  { slug: "elevenlabs", name: "ElevenLabs" },
  { slug: "resend", name: "Resend" },
  { slug: "sendgrid", name: "SendGrid" },
  { slug: "mailgun", name: "Mailgun" },
  { slug: "postmark", name: "Postmark" },
  { slug: "loops", name: "Loops" },
  { slug: "knock", name: "Knock" },
  { slug: "courier", name: "Courier" },
  { slug: "mgm", name: "MGM Resorts" },
  { slug: "pagerduty", name: "PagerDuty" },
  { slug: "opsgenie", name: "Opsgenie" },
  { slug: "incidentio", name: "Incident.io" },
  { slug: "rootly", name: "Rootly" },
  { slug: "firefox", name: "Firefox" },
  { slug: "chrome", name: "Chrome" },
  { slug: "safari", name: "Safari" },
  { slug: "opera", name: "Opera" },
  { slug: "brave", name: "Brave" },
  { slug: "edge", name: "Microsoft Edge" },
  { slug: "arc", name: "Arc" },
  { slug: "zen", name: "Zen Browser" },
  { slug: "floorp", name: "Floorp" },
  { slug: "librewolf", name: "LibreWolf" },
  { slug: "torproject", name: "Tor Browser" },
  { slug: "ungoogledchromium", name: "Ungoogled Chromium" },
  { slug: "qutebrowser", name: "qutebrowser" },
  { slug: "lynx", name: "Lynx" },
  { slug: "w3m", name: "w3m" },
  { slug: "links", name: "Links" },
  { slug: "elinks", name: "ELinks" },
  { slug: "surf", name: "surf" },
  { slug: "nyxt", name: "Nyxt" },
  { slug: "vimium", name: "Vimium" },
  { slug: "tridactyl", name: "Tridactyl" },
  { slug: "darkreader", name: "Dark Reader" },
  { slug: "ublockorigin", name: "uBlock Origin" },
  { slug: "adguard", name: "AdGuard" },
  { slug: "noscript", name: "NoScript" },
  { slug: "privacybadger", name: "Privacy Badger" },
  { slug: "decentraleyes", name: "Decentraleyes" },
  { slug: "bitwarden", name: "Bitwarden" },
  { slug: "1password", name: "1Password" },
  { slug: "dashlane", name: "Dashlane" },
  { slug: "proton", name: "Proton" },
  { slug: "protonmail", name: "Proton Mail" },
  { slug: "protonvpn", name: "Proton VPN" },
  { slug: "protoncalendar", name: "Proton Calendar" },
  { slug: "protonpass", name: "Proton Pass" },
  { slug: "protonwallet", name: "Proton Wallet" },
  { slug: "signal", name: "Signal" },
  { slug: "simplex", name: "SimpleX" },
  { slug: "session", name: "Session" },
  { slug: "element", name: "Element" },
  { slug: "matrix", name: "Matrix" },
  { slug: "rocketchat", name: "Rocket.Chat" },
  { slug: "zulip", name: "Zulip" },
  { slug: "mattermost", name: "Mattermost" },
  { slug: "wire", name: "Wire" },
  { slug: "keybase", name: "Keybase" },
  { slug: "threema", name: "Threema" },
  { slug: "wickr", name: "Wickr" },
  { slug: "jitsi", name: "Jitsi" },
  { slug: "bigbluebutton", name: "BigBlueButton" },
  { slug: "whereby", name: "Whereby" },
  { slug: "around", name: "Around" },
  { slug: "gather", name: "Gather" },
  { slug: "spatialchat", name: "SpatialChat" },
  { slug: "kumospace", name: "Kumospace" },
  { slug: "teams", name: "Microsoft Teams" },
  { slug: "chanty", name: "Chanty" },
  { slug: "flock", name: "Flock" },
  { slug: "ringcentral", name: "RingCentral" },
  { slug: "vonage", name: "Vonage" },
  { slug: "twilio", name: "Twilio" },
  { slug: "plivo", name: "Plivo" },
  { slug: "sinch", name: "Sinch" },
  { slug: "messagebird", name: "MessageBird" },
  { slug: "sendbird", name: "Sendbird" },
  { slug: "pubnub", name: "PubNub" },
  { slug: "pusher", name: "Pusher" },
  { slug: "ably", name: "Ably" },
  { slug: "stripe", name: "Stripe" },
  { slug: "square", name: "Square" },
  { slug: "razorpay", name: "Razorpay" },
  { slug: "paddle", name: "Paddle" },
  { slug: "lemonsqueezy", name: "Lemon Squeezy" },
  { slug: "gumroad", name: "Gumroad" },
  { slug: "pixela", name: "Pixela" },
  { slug: "coindesk", name: "CoinDesk" },
  { slug: "coinbase", name: "Coinbase" },
  { slug: "binance", name: "Binance" },
  { slug: "kraken", name: "Kraken" },
  { slug: "etherscan", name: "Etherscan" },
  { slug: "solana", name: "Solana" },
  { slug: "ethereum", name: "Ethereum" },
  { slug: "bitcoin", name: "Bitcoin" },
  { slug: "lightning", name: "Lightning" },
  { slug: "lnd", name: "LND" },
  { slug: "btcpayserver", name: "BTCPay Server" },
  { slug: "sparrow", name: "Sparrow" },
  { slug: "specter", name: "Specter" },
  { slug: "wasabiwallet", name: "Wasabi Wallet" },
  { slug: "samouraiwallet", name: "Samourai Wallet" },
  { slug: "muun", name: "Muun" },
  { slug: "phoenix", name: "Phoenix" },
  { slug: "breez", name: "Breez" },
  { slug: "zeusln", name: "Zeus" },
  { slug: "alby", name: "Alby" },
  { slug: "getalby", name: "Alby" },
  { slug: "nostr", name: "Nostr" },
  { slug: "damus", name: "Damus" },
  { slug: "amethyst", name: "Amethyst" },
  { slug: "primal", name: "Primal" },
  { slug: "snort", name: "Snort" },
  { slug: "zapstream", name: "Zap Stream" },
  { slug: "wavlake", name: "WavLake" },
  { slug: "podcastindex", name: "Podcast Index" },
  { slug: "fountain", name: "Fountain" },
  { slug: "castamatic", name: "Castamatic" },
  { slug: "podverse", name: "Podverse" },
  { slug: "pocketcasts", name: "Pocket Casts" },
  { slug: "overcast", name: "Overcast" },
  { slug: "castbox", name: "Castbox" },
  { slug: "anchorfm", name: "Anchor" },
  { slug: "transistor", name: "Transistor" },
  { slug: "redcircle", name: "RedCircle" },
  { slug: "megaphone", name: "Megaphone" },
  { slug: "art19", name: "ART19" },
  { slug: "simplecast", name: "Simplecast" },
  { slug: "pinecast", name: "Pinecast" },
  { slug: "captivate", name: "Captivate" },
  { slug: "buzzsprout", name: "Buzzsprout" },
  { slug: "spreaker", name: "Spreaker" },
  { slug: "mixcloud", name: "Mixcloud" },
  { slug: "soundcloud", name: "SoundCloud" },
  { slug: "audioboom", name: "Audioboom" },
  { slug: "podbean", name: "Podbean" },
  { slug: "libsyn", name: "Libsyn" },
  { slug: "blubrry", name: "Blubrry" },
  { slug: "omny", name: "Omny Studio" },
  { slug: "acast", name: "Acast" },
  { slug: "audiome", name: "Audio.me" },
  { slug: "kofi", name: "Ko-fi" },
  { slug: "patreon", name: "Patreon" },
  { slug: "buymeacoffee", name: "Buy Me a Coffee" },
  { slug: "liberapay", name: "Liberapay" },
  { slug: "opencollective", name: "Open Collective" },
  { slug: "githubsponsors", name: "GitHub Sponsors" },
  { slug: "thanks.dev", name: "Thanks.dev" },
  { slug: "polar", name: "Polar" },
  { slug: "stripe", name: "Stripe" },
  { slug: "paddle", name: "Paddle" },
  { slug: "lemonsqueezy", name: "Lemon Squeezy" },
  { slug: "gumroad", name: "Gumroad" },
  { slug: "shopify", name: "Shopify" },
  { slug: "woocommerce", name: "WooCommerce" },
  { slug: "magento", name: "Magento" },
  { slug: "bigcommerce", name: "BigCommerce" },
  { slug: "squarespace", name: "Squarespace" },
  { slug: "wix", name: "Wix" },
  { slug: "webflow", name: "Webflow" },
  { slug: "framer", name: "Framer" },
  { slug: "carrd", name: "Carrd" },
  { slug: "linktree", name: "Linktree" },
  { slug: "bio_link", name: "Bio.link" },
  { slug: "beacons", name: "Beacons" },
  { slug: "milkshake", name: "Milkshake" },
  { slug: "taplink", name: "TapLink" },
  { slug: "folks", name: "Folks" },
  { slug: "litlink", name: "LitLink" },
  { slug: "manylink", name: "ManyLink" },
  { slug: "shorby", name: "Shorby" },
  { slug: "linkinbio", name: "Linkin.bio" },
  { slug: "contactinbio", name: "Contactinbio" },
  { slug: "flowcode", name: "Flowcode" },
  { slug: "lnk.bio", name: "Lnk.Bio" },
  { slug: "quizlet", name: "Quizlet" },
  { slug: "anki", name: "Anki" },
  { slug: "remnote", name: "RemNote" },
  { slug: "roamresearch", name: "Roam Research" },
  { slug: "logseq", name: "Logseq" },
  { slug: "obsidian", name: "Obsidian" },
  { slug: "notion", name: "Notion" },
  { slug: "craft", name: "Craft" },
  { slug: "bear", name: "Bear" },
  { slug: "ulysses", name: "Ulysses" },
  { slug: "iawriter", name: "iA Writer" },
  { slug: "byword", name: "Byword" },
  { slug: "scrivener", name: "Scrivener" },
  { slug: "finaldraft", name: "Final Draft" },
  { slug: "dramatron", name: "Dramatron" },
  { slug: "manuskript", name: "Manuskript" },
  { slug: "quollwriter", name: "QuollWriter" },
  { slug: "novelcrafter", name: "NovelCrafter" },
  { slug: "ywriter", name: "yWriter" },
  { slug: "bibisco", name: "Bibisco" },
  { slug: "plottr", name: "Plottr" },
  { slug: "campfire", name: "Campfire" },
  { slug: "worldanvil", name: "World Anvil" },
  { slug: "legendkeeper", name: "LegendKeeper" },
  { slug: "kanka", name: "Kanka" },
  { slug: "obsidianmd", name: "Obsidian" },
  { slug: "foam", name: "Foam" },
  { slug: "dendron", name: "Dendron" },
  { slug: "wiki.js", name: "Wiki.js" },
  { slug: "bookstack", name: "BookStack" },
  { slug: "outline", name: "Outline" },
  { slug: "slab", name: "Slab" },
  { slug: "documenso", name: "Documenso" },
  { slug: "papermark", name: "Papermark" },
  { slug: "documate", name: "Documate" },
  { slug: "gitbook", name: "GitBook" },
  { slug: "readme", name: "ReadMe" },
  { slug: "readthedocs", name: "Read the Docs" },
  { slug: "docusaurus", name: "Docusaurus" },
  { slug: "vitepress", name: "VitePress" },
  { slug: "mkdocs", name: "MkDocs" },
  { slug: "sphinx", name: "Sphinx" },
  { slug: "antora", name: "Antora" },
  { slug: "asciidoctor", name: "Asciidoctor" },
  { slug: "adobe", name: "Adobe" },
  { slug: "adobeacrobat", name: "Adobe Acrobat" },
  { slug: "adobephotoshop", name: "Adobe Photoshop" },
  { slug: "adobeillustrator", name: "Adobe Illustrator" },
  { slug: "adobepremierepro", name: "Adobe Premiere Pro" },
  { slug: "adobeaftereffects", name: "Adobe After Effects" },
  { slug: "adobelightroom", name: "Adobe Lightroom" },
  { slug: "adobexd", name: "Adobe XD" },
  { slug: "adobefonts", name: "Adobe Fonts" },
  { slug: "adobecreativecloud", name: "Adobe Creative Cloud" },
  { slug: "affinity", name: "Affinity" },
  { slug: "affinitydesigner", name: "Affinity Designer" },
  { slug: "affinityphoto", name: "Affinity Photo" },
  { slug: "affinitypublisher", name: "Affinity Publisher" },
  { slug: "inkscape", name: "Inkscape" },
  { slug: "gimp", name: "GIMP" },
  { slug: "krita", name: "Krita" },
  { slug: "blender", name: "Blender" },
  { slug: "godot", name: "Godot" },
  { slug: "unity", name: "Unity" },
  { slug: "unrealengine", name: "Unreal Engine" },
  { slug: "threejs", name: "Three.js" },
  { slug: "babylonjs", name: "Babylon.js" },
  { slug: "pixijs", name: "PixiJS" },
  { slug: "phaser", name: "Phaser" },
  { slug: "cocos", name: "Cocos" },
  { slug: "defold", name: "Defold" },
  { slug: "love", name: "LÖVE" },
  { slug: "renpy", name: "Ren'Py" },
  { slug: "rpgmaker", name: "RPG Maker" },
  { slug: "twine", name: "Twine" },
  { slug: "ink", name: "Ink" },
  { slug: "yarnspinner", name: "Yarn Spinner" },
  { slug: "dialogic", name: "Dialogic" },
  { slug: "chatbot", name: "Chatbot" },
  { slug: "rasa", name: "Rasa" },
  { slug: "botpress", name: "Botpress" },
  { slug: "voiceflow", name: "Voiceflow" },
  { slug: "dialogflow", name: "Dialogflow" },
  { slug: "lex", name: "Amazon Lex" },
  { slug: "luis", name: "LUIS" },
  { slug: "watson", name: "IBM Watson" },
  { slug: "cohere", name: "Cohere" },
  { slug: "ai21", name: "AI21" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "openai", name: "OpenAI" },
  { slug: "mistral", name: "Mistral" },
  { slug: "perplexity", name: "Perplexity" },
  { slug: "you", name: "You.com" },
  { slug: "phind", name: "Phind" },
  { slug: "writesonic", name: "Writesonic" },
  { slug: "jasper", name: "Jasper" },
  { slug: "copy", name: "Copy.ai" },
  { slug: "rytr", name: "Rytr" },
  { slug: "sudowrite", name: "Sudowrite" },
  { slug: "novelai", name: "NovelAI" },
  { slug: "dreamstudio", name: "DreamStudio" },
  { slug: "midjourney", name: "Midjourney" },
  { slug: "dalle", name: "DALL·E" },
  { slug: "stablediffusion", name: "Stable Diffusion" },
  { slug: "comfyui", name: "ComfyUI" },
  { slug: "automatic1111", name: "Automatic1111" },
  { slug: "fooocus", name: "Fooocus" },
  { slug: "invokeai", name: "InvokeAI" },
  { slug: "kandinsky", name: "Kandinsky" },
  { slug: "adobefirefly", name: "Adobe Firefly" },
  { slug: "canva", name: "Canva" },
  { slug: "clipchamp", name: "Clipchamp" },
  { slug: "capcut", name: "CapCut" },
  { slug: "davinciresolve", name: "DaVinci Resolve" },
  { slug: "finalcutpro", name: "Final Cut Pro" },
  { slug: "imovie", name: "iMovie" },
  { slug: "shotcut", name: "Shotcut" },
  { slug: "openshot", name: "OpenShot" },
  { slug: "kdenlive", name: "Kdenlive" },
  { slug: "obsstudio", name: "OBS Studio" },
  { slug: "streamlabs", name: "Streamlabs" },
  { slug: "restream", name: "Restream" },
  { slug: "ecamm", name: "Ecamm" },
  { slug: "melty", name: "Melty" },
  { slug: "wirecast", name: "Wirecast" },
  { slug: "vmix", name: "vMix" },
  { slug: "tricaster", name: "TriCaster" },
  { slug: "atem", name: "ATEM" },
  { slug: "blackmagicdesign", name: "Blackmagic Design" },
  { slug: "magix", name: "MAGIX" },
  { slug: "vegaspro", name: "Vegas Pro" },
  { slug: "avid", name: "Avid" },
  { slug: "avidemux", name: "Avidemux" },
  { slug: "handbrake", name: "HandBrake" },
  { slug: "ffmpeg", name: "FFmpeg" },
  { slug: "youtube", name: "YouTube" },
  { slug: "vimeo", name: "Vimeo" },
  { slug: "dailymotion", name: "Dailymotion" },
  { slug: "twitch", name: "Twitch" },
  { slug: "kick", name: "Kick" },
  { slug: "rumble", name: "Rumble" },
  { slug: "odysee", name: "Odysee" },
  { slug: "lbry", name: "LBRY" },
  { slug: "peertube", name: "PeerTube" },
  { slug: "d.tube", name: "DTube" },
  { slug: "3speak", name: "3Speak" },
  { slug: "bitchute", name: "BitChute" },
  { slug: "brighteon", name: "Brighteon" },
  { slug: "roku", name: "Roku" },
  { slug: "apple", name: "Apple" },
  { slug: "appletv", name: "Apple TV" },
  { slug: "applemusic", name: "Apple Music" },
  { slug: "applepodcasts", name: "Apple Podcasts" },
  { slug: "applearcade", name: "Apple Arcade" },
  { slug: "applefitness", name: "Apple Fitness" },
  { slug: "applenews", name: "Apple News" },
  { slug: "applebooks", name: "Apple Books" },
  { slug: "applepay", name: "Apple Pay" },
  { slug: "appstore", name: "App Store" },
  { slug: "googleplay", name: "Google Play" },
  { slug: "googlepodcasts", name: "Google Podcasts" },
  { slug: "googlenews", name: "Google News" },
  { slug: "googlephotos", name: "Google Photos" },
  { slug: "googlehome", name: "Google Home" },
  { slug: "googleassistant", name: "Google Assistant" },
  { slug: "googletv", name: "Google TV" },
  { slug: "googlemessages", name: "Google Messages" },
  { slug: "googlemeet", name: "Google Meet" },
  { slug: "googleclassroom", name: "Google Classroom" },
  { slug: "googleforms", name: "Google Forms" },
  { slug: "googlesheets", name: "Google Sheets" },
  { slug: "googleslides", name: "Google Slides" },
  { slug: "googledocs", name: "Google Docs" },
  { slug: "googlekeep", name: "Google Keep" },
  { slug: "googlemaps", name: "Google Maps" },
  { slug: "googleearth", name: "Google Earth" },
  { slug: "googleads", name: "Google Ads" },
  { slug: "googleanalytics", name: "Google Analytics" },
  { slug: "googletagmanager", name: "Google Tag Manager" },
  { slug: "googleoptimize", name: "Google Optimize" },
  { slug: "googlesearchconsole", name: "Google Search Console" },
  { slug: "googlewebmaster", name: "Google Webmaster" },
  { slug: "googlemybusiness", name: "Google My Business" },
  { slug: "googleworkspace", name: "Google Workspace" },
  { slug: "googleadmin", name: "Google Admin" },
  { slug: "googlecloud", name: "Google Cloud" },
  { slug: "googledeveloper", name: "Google Developer" },
  { slug: "googlecolab", name: "Google Colab" },
  { slug: "googletranslate", name: "Google Translate" },
  { slug: "googlelens", name: "Google Lens" },
  { slug: "googlebard", name: "Google Bard" },
  { slug: "googlegemini", name: "Google Gemini" },
  { slug: "googledeepmind", name: "Google DeepMind" },
  { slug: "microsoft", name: "Microsoft" },
  { slug: "microsoft365", name: "Microsoft 365" },
  { slug: "microsoftoffice", name: "Microsoft Office" },
  { slug: "microsoftword", name: "Microsoft Word" },
  { slug: "microsoftexcel", name: "Microsoft Excel" },
  { slug: "microsoftpowerpoint", name: "Microsoft PowerPoint" },
  { slug: "microsoftoutlook", name: "Microsoft Outlook" },
  { slug: "microsoftonenote", name: "Microsoft OneNote" },
  { slug: "microsoftonedrive", name: "Microsoft OneDrive" },
  { slug: "microsoftsharepoint", name: "Microsoft SharePoint" },
  { slug: "microsoftteams", name: "Microsoft Teams" },
  { slug: "microsoftcopilot", name: "Microsoft Copilot" },
  { slug: "microsoftbing", name: "Microsoft Bing" },
  { slug: "microsoftedge", name: "Microsoft Edge" },
  { slug: "microsoftdefender", name: "Microsoft Defender" },
  { slug: "microsoftazure", name: "Microsoft Azure" },
  { slug: "microsoftsqlserver", name: "Microsoft SQL Server" },
  { slug: "microsoftvisio", name: "Microsoft Visio" },
  { slug: "microsoftproject", name: "Microsoft Project" },
  { slug: "microsoftpublisher", name: "Microsoft Publisher" },
  { slug: "microsoftaccess", name: "Microsoft Access" },
  { slug: "microsoftpowerapps", name: "Microsoft Power Apps" },
  { slug: "microsoftpowerautomate", name: "Microsoft Power Automate" },
  { slug: "microsoftpowerbi", name: "Microsoft Power BI" },
  { slug: "dynamics365", name: "Dynamics 365" },
  { slug: "linkedin", name: "LinkedIn" },
  { slug: "skype", name: "Skype" },
  { slug: "yammer", name: "Yammer" },
  { slug: "flipgrid", name: "Flipgrid" },
  { slug: "sway", name: "Sway" },
  { slug: "stream", name: "Microsoft Stream" },
  { slug: "forms", name: "Microsoft Forms" },
  { slug: "lists", name: "Microsoft Lists" },
  { slug: "planner", name: "Microsoft Planner" },
  { slug: "todo", name: "Microsoft To Do" },
  { slug: "clipy", name: "Clipy" },
  { slug: "flycut", name: "Flycut" },
  { slug: "maccy", name: "Maccy" },
  { slug: "paste", name: "Paste" },
  { slug: "pasty", name: "Pasty" },
  { slug: "copyclip", name: "CopyClip" },
  { slug: "unclutter", name: "Unclutter" },
  { slug: "yoink", name: "Yoink" },
  { slug: "dropover", name: "Dropover" },
  { slug: "dropzone", name: "Dropzone" },
  { slug: "forklift", name: "ForkLift" },
  { slug: "transmit", name: "Transmit" },
  { slug: "cyberduck", name: "Cyberduck" },
  { slug: "filezilla", name: "FileZilla" },
  { slug: "winscp", name: "WinSCP" },
  { slug: "putty", name: "PuTTY" },
  { slug: "kitty", name: "KiTTY" },
  { slug: "mosh", name: "Mosh" },
  { slug: "terminal", name: "Terminal" },
  { slug: "iterm2", name: "iTerm2" },
  { slug: "alacritty", name: "Alacritty" },
  { slug: "kitty", name: "Kitty" },
  { slug: "wezterm", name: "WezTerm" },
  { slug: "foot", name: "Foot" },
  { slug: "st", name: "st (simple terminal)" },
  { slug: "urxvt", name: "URxvt" },
  { slug: "rxvt", name: "Rxvt" },
  { slug: "xterm", name: "xterm" },
  { slug: "gnometerminal", name: "GNOME Terminal" },
  { slug: "kdekonsole", name: "Konsole" },
  { slug: "lxterminal", name: "LXTerminal" },
  { slug: "xfce4terminal", name: "XFCE Terminal" },
  { slug: "sakura", name: "Sakura" },
  { slug: "terminator", name: "Terminator" },
  { slug: "tilix", name: "Tilix" },
  { slug: "guake", name: "Guake" },
  { slug: "yakuake", name: "Yakuake" },
  { slug: "tilda", name: "Tilda" },
  { slug: "coolterm", name: "Cool Retro Term" },
  { slug: "hyper", name: "Hyper" },
  { slug: "warp", name: "Warp" },
  { slug: "waves", name: "Waves" },
  { slug: "tabby", name: "Tabby" },
  { slug: "terminus", name: "Terminus" },
  { slug: "ssh", name: "SSH" },
  { slug: "openssh", name: "OpenSSH" },
  { slug: "dropbear", name: "Dropbear" },
  { slug: "mosh", name: "Mosh" },
  { slug: "autossh", name: "AutoSSH" },
]

export function brandIconUrl(slug, sectionColor, iconStyle) {
  if (!slug) return null
  const base = `https://cdn.simpleicons.org/${slug}`
  if (iconStyle === "section" && sectionColor)
    return `${base}/${sectionColor.replace("#", "")}`
  return base
}

export function faviconUrl(link) {
  try {
    const host = new URL(link.url).hostname
    return `https://www.google.com/s2/favicons?domain=${host}&sz=32`
  } catch {
    return ""
  }
}

export async function fetchSvgIcons(slugs) {
  if (!slugs.size) return {}
  const entries = await Promise.all(
    [...slugs].map(async (slug) => {
      try {
        const res = await fetch(`https://cdn.simpleicons.org/${slug}`)
        if (!res.ok) return [slug, null]
        return [slug, await res.text()]
      } catch {
        return [slug, null]
      }
    })
  )
  return Object.fromEntries(entries)
}
